# Generated by Django 5.1.3 on 2024-11-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=dict),
        ),
    ]
