# Generated by Django 5.1.3 on 2024-11-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_remove_product_colors_product_image_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_products'),
        ),
    ]
