# Generated by Django 5.1.3 on 2024-11-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0011_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
