# Generated by Django 5.1.3 on 2024-11-29 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_customuser_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('verified', 'verified'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('phone_no', models.CharField(max_length=255)),
                ('tax_id_number', models.CharField(max_length=255)),
                ('gst_vat_registration', models.CharField(max_length=255)),
                ('pan_card', models.FileField(upload_to='kyc/government_id/')),
                ('adhar_card', models.FileField(upload_to='kyc/address_proof/')),
                ('bank_account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
