# Generated by Django 5.1.3 on 2024-12-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0015_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_colors/'),
        ),
    ]
