# Generated by Django 5.1.3 on 2024-12-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
