# Generated by Django 5.1.3 on 2024-12-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0018_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
