# Generated by Django 5.1.3 on 2024-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('THIRDPARTY', 'Thirdparty'), ('SELF-FULLFILMENT', 'Self-fullfilment')], default='THIRDPARTY', max_length=20),
        ),
    ]
