from django.contrib import admin
from django.urls import path
from .views import CustomUserRegistrationView,SessionLoginView,SessionLogoutView,ProductList,getProducts,ProductsByCategoryView,CartCreateView,CartListView,testview,deletecart,Viewcategories,SearchProductView,Profile,profileEdit,UpdateProfileView,get_csrf_token,CartCount,ContactAPIView,Kyc,GetKycStatus,summary_api,CreateProductWithColorsView,GetVendorProducts,RetriveVedorProducts,UpdateVedorProducts,OrderCreateView,Checkout,user_orders,vendor_orders,GiveFeedback,Categorys,OrderStatuss,feedback_api
urlpatterns = [
    path('registration/', CustomUserRegistrationView.as_view()),
    path('login/', SessionLoginView.as_view()),
    path('logout/', SessionLogoutView.as_view()),
    path('product/', ProductList.as_view()),
    path('getproduct/<int:id>',getProducts.as_view()),
    path('products/category/<str:category_name>/', ProductsByCategoryView.as_view(), name='products-by-category'),
    path('cartcreate/',CartCreateView.as_view()),
    path('cartlist/<str:username>/',CartListView.as_view()),
    path('test/',testview.as_view()),
    path('deletecart/<int:id>/',deletecart.as_view()),
    path('viewcat/',Viewcategories.as_view()),
    path('serchproduct/', SearchProductView.as_view(), name='search-product'),
    path('profile/', Profile.as_view(), name="profile"),
    path('profileUpdate/',UpdateProfileView.as_view()),
    path('csrf/',get_csrf_token),
    path('cartcount/',CartCount),
    path('contact/',ContactAPIView.as_view()),
    path('kyc/',Kyc.as_view()),
    path('kycstatus/',GetKycStatus.as_view()),
    path('summary/',summary_api),
    path('addProduct/',CreateProductWithColorsView.as_view()),
    path('vendorproducts/',GetVendorProducts.as_view()),
    path('vendorproducts/<int:id>',RetriveVedorProducts.as_view()),
    path('updatevendorproducts/<int:id>',UpdateVedorProducts.as_view()),
    path('createorder/',OrderCreateView.as_view()),
    path('checkout/',Checkout.as_view()),
    path('orderss/',user_orders),
    path('vendororders/',vendor_orders),
    path('feedback/',GiveFeedback.as_view()),
    path('categories/',Categorys.as_view()),
    path('orderstatus/<int:id>/',OrderStatuss.as_view()),
    path('feedbackvendor/',feedback_api),
]